@startuml
Budget <|-- Income
Budget <|-- Expenses
Expenses <|-- SAVINGS
Expenses <|-- Bills
Expenses <|-- Lifestyle
Expenses <- Needs: ...
note right: Groceries. Housing.  Basic utilities. Transportation. Insurance.




@enduml